#!/usr/bin/env bash

set -u

output_file=''
method=GET
max_time=''
response_body=${MOCK_CURL_BODY:-}
response_status=${MOCK_CURL_STATUS:-200}

while (($#)); do
  case $1 in
    --output)
      shift
      output_file=$1
      ;;
    --request)
      shift
      method=$1
      ;;
    --max-time)
      shift
      max_time=$1
      ;;
    --connect-timeout|--write-out|--header|--data-binary)
      shift
      ;;
    --silent|--show-error) ;;
    http://*) ;;
  esac
  shift
done

if [[ -n ${MOCK_CURL_MAX_TIME_LOG:-} ]]; then
  printf '%s\n' "$max_time" >>"$MOCK_CURL_MAX_TIME_LOG"
fi

if [[ -n ${MOCK_CURL_CALL_LOG:-} ]]; then
  printf '%s\n' "$method" >>"$MOCK_CURL_CALL_LOG"
fi

if [[ -n ${MOCK_CURL_RESPONSE_QUEUE:-} &&
      -s ${MOCK_CURL_RESPONSE_QUEUE:-} ]]; then
  IFS='|' read -r response_status response_body <"$MOCK_CURL_RESPONSE_QUEUE"
  command tail -n +2 "$MOCK_CURL_RESPONSE_QUEUE" \
    >"${MOCK_CURL_RESPONSE_QUEUE}.next"
  command mv "${MOCK_CURL_RESPONSE_QUEUE}.next" "$MOCK_CURL_RESPONSE_QUEUE"
fi

if [[ -n ${MOCK_CURL_REQUIRED_TIMEOUT:-} ]] &&
   ((max_time < MOCK_CURL_REQUIRED_TIMEOUT)); then
  exit 28
fi

if [[ $response_status == 000 ]]; then
  exit 7
fi

if [[ -n $output_file ]]; then
  if [[ $method == GET ]]; then
    if [[ -n $response_body ]]; then
      printf '%s' "$response_body" >"$output_file"
    else
      printf '%s' '{"name":"test-profile"}' >"$output_file"
    fi
  else
    printf '%s' "$response_body" >"$output_file"
  fi
fi

printf '%s' "$response_status"
